/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufjf.lp3;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author igor
 */
public class JanelaTabela extends javax.swing.JFrame {

   private final List<Pessoa> pessoas;

   /**
    * Creates new form JanelaTabela
    */
   public JanelaTabela(List<Pessoa> pessoas) {
      this.pessoas = pessoas;
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      txtNome = new javax.swing.JTextField();
      btnAdicionar = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      tblNomes = new javax.swing.JTable();
      txtEmail = new javax.swing.JTextField();
      btnRemover = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Exemplo de Tabela");

      txtNome.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtNomeActionPerformed(evt);
         }
      });

      btnAdicionar.setText("Adicionar");
      btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAdicionarActionPerformed(evt);
         }
      });

      tblNomes.setModel(new PessoaTableModel(this.pessoas));
      tblNomes.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblNomesMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(tblNomes);

      txtEmail.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtEmailActionPerformed(evt);
         }
      });

      btnRemover.setText("Remover");
      btnRemover.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRemoverActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(btnAdicionar))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(btnRemover)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnAdicionar)
               .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRemover)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtNomeActionPerformed

   private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
      PessoaTableModel modelo = (PessoaTableModel) tblNomes.getModel();
      if (tblNomes.getSelectedRowCount() > 0) {
         Pessoa p = pessoas.get(tblNomes.getSelectedRow());
         p.setNome(txtNome.getText());
         p.setEmail(txtEmail.getText());
         modelo.fireTableDataChanged();
      } else {
         Pessoa p = new Pessoa();
         p.setNome(txtNome.getText());
         p.setEmail(txtEmail.getText());
         pessoas.add(p);
         modelo.fireTableDataChanged();
      }
      txtNome.setText("");
      txtEmail.setText("");
      txtNome.requestFocus();
      tblNomes.clearSelection();
   }//GEN-LAST:event_btnAdicionarActionPerformed

   private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_txtEmailActionPerformed

   private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
      PessoaTableModel modelo = (PessoaTableModel) tblNomes.getModel();
      if (tblNomes.getSelectedRowCount() > 0) {
         pessoas.remove(tblNomes.getSelectedRow());
         txtNome.setText("");
         txtEmail.setText("");
         tblNomes.clearSelection();
         modelo.fireTableDataChanged();
      }
   }//GEN-LAST:event_btnRemoverActionPerformed

   private void tblNomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNomesMouseClicked
      if (tblNomes.getSelectedRowCount() > 0) {
         PessoaTableModel modelo = (PessoaTableModel) tblNomes.getModel();
         Integer linha = tblNomes.getSelectedRow();
         txtNome.setText((String) modelo.getValueAt(linha, 0));
         txtEmail.setText((String) modelo.getValueAt(linha, 1));
         btnAdicionar.setText("Alterar");
      }else{
         txtNome.setText("");
         txtEmail.setText("");

         btnAdicionar.setText("Adicionar");
      }
   }//GEN-LAST:event_tblNomesMouseClicked

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      List<Pessoa> pessoas = new ArrayList<>();
      pessoas.add(new Pessoa("Fulano", "fulano@ufjf.br"));
      pessoas.add(new Pessoa("Beltrano", "beltrano@ufjf.br"));
      pessoas.add(new Pessoa("Ciclano", "ciclano@ufjf.br"));
      pessoas.add(new Pessoa("Ciclano 2", "ciclano@ufjf.br"));
      
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(JanelaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(JanelaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(JanelaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(JanelaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            JanelaTabela janela = new JanelaTabela(pessoas);
            janela.setLocationRelativeTo(null);
            janela.setVisible(true);

         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAdicionar;
   private javax.swing.JButton btnRemover;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable tblNomes;
   private javax.swing.JTextField txtEmail;
   private javax.swing.JTextField txtNome;
   // End of variables declaration//GEN-END:variables
}
